# Generated by Django 4.2.2 on 2026-02-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "permissions": [("can_view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
